name: build
on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        artifact_name:
          - linux-cpu
          - linux-nvidia
          - windows-cpu
          - windows-nvidia
    steps:
      - uses: actions/checkout@v2

      - run: |
          mkdir -p artifact
          fallocate -l 1G artifact/bigzero.img

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            artifact/

  upload-to-release:
    if: github.event.release.tag_name != ''
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        artifact_name:
          - linux-cpu
          - linux-nvidia
          - windows-cpu
          - windows-nvidia
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              p7zip-full

      - name: Download and extract artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}/

      - name: Rearchive and split artifact
        run: |
          # compressed to artifact.7z.001, artifact.7z.002, ...
          # remove -mx=0 for production (uncompress option)
          7z -r -v500m -mx=0 a "${{ matrix.artifact_name }}.7z" "${{ matrix.artifact_name }}/"

      - name: Upload splitted archives to Release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }} # == github.event.release.tag_name
          file_glob: true
          file: "./${{ matrix.artifact_name }}.7z.*"
